{
 "title": "users-service dashboard",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "total gRPC calls",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 0 },
   "targets": [
    { "expr": "grpc_calls" }
   ]
  },
  {
   "title": "failed gRPC calls",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 4, "y": 0 },
   "targets": [
    { "expr": "failed_grpc_calls" }
   ]
  },
  {
   "title": "average gRPC request duration (seconds)",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 8, "y": 0 },
   "targets": [
    {
     "expr": "(rate(grpc_call_duration_milliseconds_sum[5m])\n /\nrate(grpc_call_duration_milliseconds_count[5m]))\n/ 1000"
    }
   ]
  }
 ]
}