version: '3.4'

services:
  api:
    image: api
    build:
      context: .
      dockerfile: src/microservices/users/src/Api/Dockerfile
    ports:
      - 80
      - 5001
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
      - ASPNETCORE_URLS=http://+:5001
    volumes:
      - ~/.vsdbg:/remote_debugger
