# docker-compose -f docker-compose.yaml -f docker-compose.dev.yaml up -d

version: '3.7'

services: 
    users-service:
        ports: 
            - "5000:80"
            - "5001:5001"
        environment:      
            - ASPNETCORE_ENVIRONMENT=${ASPNETCORE_ENVIRONMENT}
            - ASPNETCORE_URLS=http://*:80