# docker-compose -f docker-compose.yaml -f docker-compose.dev.yaml up -d

version: '3.7'

services: 
    users-service:
        ports: 
            - "5000:80"
            - "5001:5001"
        environment:      
            - ASPNETCORE_ENVIRONMENT=${ASPNETCORE_ENVIRONMENT}
            - ASPNETCORE_URLS=http://*:80
            - jaeger__enabled=true
            - jaeger__serviceName=users-service
            - jaeger__udpHost=jaeger
            - jaeger__udpPort=6831
            - jaeger__maxPacketSize=0
            - jaeger__sampler=const