# docker-compose -f docker-compose.yml -f docker-compose.dev.yml up -d

version: '3.7'

services: 
    users-service:
        ports: 
            - "5000:80"
        environment:      
            - ASPNETCORE_ENVIRONMENT=${ASPNETCORE_ENVIRONMENT}
            - ASPNETCORE_URLS=http://*:80