version: '3.7'
services:
  jaeger:
    image: jaegertracing/all-in-one:latest
    ports:
      - "6831:6831/udp"
      - "16686:16686"
      - "5778:5778"

networks:
  default:
    external:
      name: portfolio-manager-network
