name: .NET Core

on:
  push:
    branches:
      - master
      - github-actions
  pull_request:
    branches: 
      - master
      - github-actions

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      
    - uses: actions/checkout@v2

    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.101

    - name: Install dependencies
      run: dotnet restore src/microservices/users/src/Api/

    - name: Build
      run: dotnet build src/microservices/users/src/Api/ --configuration Release --no-restore

    - name: Run unit tests
      run: dotnet test src/microservices/users/tests/UnitTests/ --verbosity normal

    - name: Run integration tests
      run: dotnet test src/microservices/users/tests/IntegrationTests/ --verbosity normal

    - name: Run functional tests
      run: dotnet test src/microservices/users/tests/FunctionalTests/ --verbosity normal
